Repository Project-Unifest/unifest-android, pull requests merged in 2024-10, with the labels that each got.

#273 [feat] stamp 화면 API 연동, 한경대 -> 한국교통대 migration
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/AndroidApplicationComposeConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposeConventionPlugin.kt
  build-logic/src/main/kotlin/com/unifest/android/Android.kt
  build-logic/src/main/kotlin/com/unifest/android/Compose.kt
  build-logic/src/main/kotlin/com/unifest/android/Plugins.kt
  build.gradle.kts
  core/common/src/main/kotlin/com/unifest/android/core/common/ErrorResponse.kt
  core/common/src/main/kotlin/com/unifest/android/core/common/HandleQRException.kt
  core/common/src/main/res/values/strings.xml
  core/data/src/main/kotlin/com/unifest/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/BoothMapper.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/StampRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/StampRepositoryImpl.kt
  core/designsystem/src/main/res/drawable/ic_qr_scan_crosshair.xml
  core/designsystem/src/main/res/values/strings.xml
  core/model/src/main/kotlin/com/unifest/android/core/model/StampBoothModel.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/request/RegisterStampRequest.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/BoothResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/CollectedStampCountResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/booth/BoothDetailResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/booth/BoothResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/booth/LikeBoothResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/booth/StampBoothsResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/service/UnifestService.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainTab.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/viewmodel/SplashViewModel.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/QRScanActivity.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/QRScanScreen.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/StampScreen.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/component/StampBoothBottomSheet.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/component/StampBoothItem.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/preview/StampPreviewParameterProvider.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanUiAction.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanUiEvent.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanUiState.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanViewModel.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampUiState.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampViewModel.kt
  feature/stamp/src/main/res/values/colors.xml
  feature/stamp/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement, help wanted, design

#275 release v1.2.1
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/AndroidApplicationComposeConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposeConventionPlugin.kt
  build-logic/src/main/kotlin/com/unifest/android/Android.kt
  build-logic/src/main/kotlin/com/unifest/android/Compose.kt
  build-logic/src/main/kotlin/com/unifest/android/Plugins.kt
  build.gradle.kts
  core/common/src/main/kotlin/com/unifest/android/core/common/ErrorResponse.kt
  core/common/src/main/kotlin/com/unifest/android/core/common/HandleQRException.kt
  core/common/src/main/res/values/strings.xml
  core/data/src/main/kotlin/com/unifest/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/BoothMapper.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/StampRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/StampRepositoryImpl.kt
  core/designsystem/src/main/res/drawable/ic_qr_scan_crosshair.xml
  core/designsystem/src/main/res/values/strings.xml
  core/model/src/main/kotlin/com/unifest/android/core/model/StampBoothModel.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/request/RegisterStampRequest.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/BoothResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/CollectedStampCountResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/booth/BoothDetailResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/booth/BoothResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/booth/LikeBoothResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/booth/StampBoothsResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/service/UnifestService.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainTab.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/viewmodel/SplashViewModel.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/QRScanActivity.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/QRScanScreen.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/StampScreen.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/component/StampBoothBottomSheet.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/component/StampBoothItem.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/preview/StampPreviewParameterProvider.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanUiAction.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanUiEvent.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanUiState.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanViewModel.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampUiState.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampViewModel.kt
  feature/stamp/src/main/res/values/colors.xml
  feature/stamp/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: product, skip-ci

#276 [fix] 웨이팅 처리 및 부스 종류 변경 관련 QA
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/MyWaitingMapper.kt
  core/designsystem/src/main/res/drawable/ic_marker_bar.xml
  core/designsystem/src/main/res/drawable/ic_marker_bar_selected.xml
  core/designsystem/src/main/res/drawable/ic_marker_event.xml
  core/designsystem/src/main/res/drawable/ic_marker_event_selected.xml
  core/designsystem/src/main/res/drawable/ic_marker_normal.xml
  core/designsystem/src/main/res/drawable/ic_marker_normal_selected.xml
  core/network/src/main/kotlin/com/unifest/android/core/network/response/MyWaitingResponse.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/BoothFilterChips.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/WaitingDialog.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothLocationScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiState.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/main/src/main/res/drawable-night/ic_selected_stamp.xml
  feature/main/src/main/res/drawable-night/ic_stamp.xml
  feature/map/src/main/kotlin/com/unifest/android/feature/map/component/MapTopAppBar.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/WaitingScreen.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/component/WaitingInfoItem.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/viewmodel/WaitingViewModel.kt
Labels: enhancement, design

#278 [fix] 스탬프 등록이 성공 했을 때, 스탬프 화면으로 돌아가 새로고침이 되지 않는 문제 해결
  core/common/src/main/kotlin/com/unifest/android/core/common/ErrorResponse.kt
  core/common/src/main/kotlin/com/unifest/android/core/common/HandleQRException.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/QRScanActivity.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/QRScanScreen.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/StampScreen.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanUiEvent.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanUiState.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanViewModel.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampUiState.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampViewModel.kt
Labels: bug, design, hotfix

#277 [design] 웨이팅탭에 새로고침 버튼 추가
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/WaitingScreen.kt
  feature/waiting/src/main/res/drawable/ic_refresh.xml
  feature/waiting/src/main/res/values/strings.xml
Labels: enhancement

#279 [fix] QA: 학교명을 통한 API 호출 로직 수정
  feature/festival/src/main/kotlin/com/unifest/android/feature/festival/viewmodel/FestivalViewModel.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/viewmodel/SplashViewModel.kt
  feature/stamp/src/main/res/values/strings.xml
Labels: bug, hotfix

#280 release v1.2.2
  core/common/src/main/kotlin/com/unifest/android/core/common/ErrorResponse.kt
  core/common/src/main/kotlin/com/unifest/android/core/common/HandleQRException.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/MyWaitingMapper.kt
  core/designsystem/src/main/res/drawable/ic_marker_bar.xml
  core/designsystem/src/main/res/drawable/ic_marker_bar_selected.xml
  core/designsystem/src/main/res/drawable/ic_marker_event.xml
  core/designsystem/src/main/res/drawable/ic_marker_event_selected.xml
  core/designsystem/src/main/res/drawable/ic_marker_normal.xml
  core/designsystem/src/main/res/drawable/ic_marker_normal_selected.xml
  core/network/src/main/kotlin/com/unifest/android/core/network/response/MyWaitingResponse.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/BoothFilterChips.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/WaitingDialog.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothLocationScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiState.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/festival/src/main/kotlin/com/unifest/android/feature/festival/viewmodel/FestivalViewModel.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/main/src/main/res/drawable-night/ic_selected_stamp.xml
  feature/main/src/main/res/drawable-night/ic_stamp.xml
  feature/map/src/main/kotlin/com/unifest/android/feature/map/component/MapTopAppBar.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/viewmodel/SplashViewModel.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/QRScanActivity.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/QRScanScreen.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/StampScreen.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanUiEvent.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanUiState.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanViewModel.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampUiState.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampViewModel.kt
  feature/stamp/src/main/res/values/strings.xml
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/WaitingScreen.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/component/WaitingInfoItem.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/viewmodel/WaitingViewModel.kt
  feature/waiting/src/main/res/drawable/ic_refresh.xml
  feature/waiting/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: product, skip-ci

#281 [refactor] FCM Service 수신 로직 Activity 에서 Composable 내부로 이동
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/unifest/android/service/UnifestFirebaseMessagingService.kt
  app/src/main/res/values/strings.xml
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/AndroidApplicationComposeConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposeConventionPlugin.kt
  build-logic/src/main/kotlin/com/unifest/android/Android.kt
  build-logic/src/main/kotlin/com/unifest/android/Compose.kt
  build.gradle.kts
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainActivity.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainViewModel.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/SplashActivity.kt
  gradle/libs.versions.toml
Labels: bug, refactor

#283 release v1.2.3
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/unifest/android/service/UnifestFirebaseMessagingService.kt
  app/src/main/res/values/strings.xml
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/AndroidApplicationComposeConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposeConventionPlugin.kt
  build-logic/src/main/kotlin/com/unifest/android/Android.kt
  build-logic/src/main/kotlin/com/unifest/android/Compose.kt
  build.gradle.kts
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/WaitingDialog.kt
  core/ui/src/main/res/values/strings.xml
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/navigation/BoothNavigation.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiAction.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiEvent.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiState.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/booth/src/main/res/values/strings.xml
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainActivity.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainViewModel.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/SplashActivity.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/WaitingScreen.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/viewmodel/WaitingUiAction.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/viewmodel/WaitingViewModel.kt
  gradle/libs.versions.toml
Labels: product, skip-ci

#285 [fix] issue #270
  app/proguard-rules.pro
  build-logic/build.gradle.kts
  build-logic/settings.gradle.kts
  build-logic/src/main/kotlin/AndroidApplicationComposeConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidFirebaseConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidHiltConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposeConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidRetrofitConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidRoomConventionPlugin.kt
  build-logic/src/main/kotlin/JvmKotlinConventionPlugin.kt
  build-logic/src/main/kotlin/com/unifest/android/Compose.kt
  build-logic/src/main/kotlin/com/unifest/android/convention/Android.kt
  build-logic/src/main/kotlin/com/unifest/android/convention/Compose.kt
  build-logic/src/main/kotlin/com/unifest/android/convention/Config.kt
  build-logic/src/main/kotlin/com/unifest/android/convention/Dependencies.kt
  build-logic/src/main/kotlin/com/unifest/android/convention/Extensions.kt
  build-logic/src/main/kotlin/com/unifest/android/convention/Plugins.kt
  build.gradle.kts
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/AutoResizedText.kt
  core/navigation/build.gradle.kts
  core/navigation/src/main/kotlin/com/unifest/android/core/navigation/RouteModel.kt
  core/network/build.gradle.kts
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/navigation/BoothNavigation.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/navigation/HomeNavigation.kt
  feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/navigation/LikedBoothNavigation.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainTab.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/navigation/MapNavigation.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/component/FestivalItem.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/component/MenuItem.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/navigation/MenuNavigation.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/preview/MenuPreviewParameterProvider.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiState.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/StampScreen.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/navigation/StampNavigation.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampViewModel.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/navigation/WaitingNavigation.kt
  gradle/libs.versions.toml
Labels: bug, refactor

#286 release v1.2.4
  README.md
  app/proguard-rules.pro
  build-logic/build.gradle.kts
  build-logic/settings.gradle.kts
  build-logic/src/main/kotlin/AndroidApplicationComposeConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidFirebaseConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidHiltConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposeConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidRetrofitConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidRoomConventionPlugin.kt
  build-logic/src/main/kotlin/JvmKotlinConventionPlugin.kt
  build-logic/src/main/kotlin/com/unifest/android/Compose.kt
  build-logic/src/main/kotlin/com/unifest/android/convention/Android.kt
  build-logic/src/main/kotlin/com/unifest/android/convention/Compose.kt
  build-logic/src/main/kotlin/com/unifest/android/convention/Config.kt
  build-logic/src/main/kotlin/com/unifest/android/convention/Dependencies.kt
  build-logic/src/main/kotlin/com/unifest/android/convention/Extensions.kt
  build-logic/src/main/kotlin/com/unifest/android/convention/Plugins.kt
  build.gradle.kts
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/AutoResizedText.kt
  core/navigation/build.gradle.kts
  core/navigation/src/main/kotlin/com/unifest/android/core/navigation/RouteModel.kt
  core/network/build.gradle.kts
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/navigation/BoothNavigation.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/navigation/HomeNavigation.kt
  feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/navigation/LikedBoothNavigation.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainTab.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/navigation/MapNavigation.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/component/FestivalItem.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/component/MenuItem.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/navigation/MenuNavigation.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/preview/MenuPreviewParameterProvider.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiState.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/StampScreen.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/navigation/StampNavigation.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampViewModel.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/navigation/WaitingNavigation.kt
  gradle/libs.versions.toml
Labels: product, skip-ci
