Repository Project-Unifest/unifest-android, pull requests merged in 2024-09, with the labels that each got.

#249 [fix] ToolTip 및 TextField 관련 이슈 해결
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/SearchTextField.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/Tooltip.kt
  gradle/libs.versions.toml
Labels: bug, design

#252 [feat] Stamp 모듈 화면 구성 및 화면 이동 로직 구현
  app/src/main/AndroidManifest.xml
  core/common/src/main/kotlin/com/unifest/android/core/common/utils/DpToPx.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/Dialog.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/HorizontalDivider.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/theme/Font.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/drawable/ic_arrow_right.xml
  core/designsystem/src/main/res/drawable/ic_checked_stamp.png
  core/designsystem/src/main/res/drawable/ic_refresh.xml
  core/designsystem/src/main/res/drawable/ic_selected_stamp.xml
  core/designsystem/src/main/res/drawable/ic_stamp.xml
  core/designsystem/src/main/res/drawable/ic_unchecked_stamp.png
  core/designsystem/src/main/res/font/pretendard_light.otf
  core/designsystem/src/main/res/values/strings.xml
  core/model/src/main/kotlin/com/unifest/android/core/model/StampBoothModel.kt
  core/navigation/src/main/kotlin/com/unifest/android/core/navigation/RouteModel.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/PermissionDialog.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/festival/src/main/kotlin/com/unifest/android/feature/festival/FestivalBottomSheet.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainTab.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/component/MainBottomBar.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/stamp/.gitignore
  feature/stamp/build.gradle.kts
  feature/stamp/src/main/AndroidManifest.xml
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/QRScanActivity.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/QRScanScreen.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/StampScreen.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/component/StampBoothBottomSheet.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/component/StampBoothItem.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/component/StampButton.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/navigation/StampNavigation.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/preview/StampPreviewParameterProvider.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanUiAction.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanUiEvent.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanUiState.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanViewModel.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampUiAction.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampUiEvent.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampUiState.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampViewModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement, design

#253 [fix] 확성기 관련 API endpoint 변경 사항 반영, 권한 요청 플로우 관련 문제 해결
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/LikedFestivalRepositoryImpl.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/request/LikedFestivalRequest.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/service/UnifestService.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/preview/MapPreviewParameterProvider.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/QRScanActivity.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/StampScreen.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/StampViewModel.kt
Labels: bug, enhancement, hotfix

#262 [feat] 클러스터링 마커 구현
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/CircularOutlineButton.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/Tooltip.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/drawable/ic_cluster_icon.xml
  core/designsystem/src/main/res/values/strings.xml
  core/network/src/main/kotlin/com/unifest/android/core/network/service/UnifestService.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedFestivalGrid.kt
  feature/festival/src/main/kotlin/com/unifest/android/feature/festival/viewmodel/FestivalViewModel.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/component/IncomingFestivalCard.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainTab.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/model/BoothMapModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiAction.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/SplashScreen.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/viewmodel/SplashViewModel.kt
  feature/stamp/build.gradle.kts
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/StampScreen.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/component/WaitingInfoItem.kt
Labels: bug, enhancement, design

#264 [style] 업데이트 전 UI 관련 디테일 수정
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/WaitingDialog.kt
  feature/festival/src/main/kotlin/com/unifest/android/feature/festival/FestivalBottomSheet.kt
Labels: design

#263 [fix] 관심 축제 추가 버튼 주석처리, 운영시간 관련 처리
  core/network/src/main/kotlin/com/unifest/android/core/network/response/BoothResponse.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/component/BoothDescription.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/component/MenuStatusTag.kt
  feature/booth/src/main/res/values/strings.xml
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/component/FestivalScheduleItem.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/component/WaitingInfoItem.kt
Labels: enhancement

#267 [feat] 관심 축제 웨이팅 푸시 알림 기능 구현(웨이팅 추가 API request 변경, 토픽 등록, 알림 클릭시 화면 이동 로직 구현)
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/kotlin/com/unifest/android/service/UnifestFirebaseMessagingService.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/BoothRepositoryImpl.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/MessagingRepositoryImpl.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/WaitingRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/WaitingRepositoryImpl.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/TokenDataSource.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/request/BoothWaitingRequest.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/intro/build.gradle.kts
  feature/intro/proguard-rules.pro
  feature/main/build.gradle.kts
  feature/main/proguard-rules.pro
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainActivity.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainViewModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/splash/build.gradle.kts
  feature/splash/proguard-rules.pro
  feature/stamp/build.gradle.kts
  feature/stamp/proguard-rules.pro
Labels: enhancement

#268 [feat] 클러스터링 활성화/비활성화 메뉴 옵션 추가, 푸시 알림을 클릭했을 때 화면 이동 되지 않는 문제 해결
  app/proguard-rules.pro
  app/src/main/kotlin/com/unifest/android/initializer/FirebaseMessagingInitializer.kt
  app/src/main/kotlin/com/unifest/android/service/UnifestFirebaseMessagingService.kt
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/AndroidApplicationComposeConventionPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposeConventionPlugin.kt
  build-logic/src/main/kotlin/com/unifest/android/Android.kt
  build-logic/src/main/kotlin/com/unifest/android/Compose.kt
  build-logic/src/main/kotlin/com/unifest/android/Extensions.kt
  build-logic/src/main/kotlin/com/unifest/android/Plugins.kt
  build.gradle.kts
  core/data/src/main/kotlin/com/unifest/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/LikedFestivalRepositoryImpl.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/SettingRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/SettingRepositoryImpl.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/SettingDataSource.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/SettingDataSourceImpl.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/di/DataSourceModule.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/di/DataStoreModule.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/di/DataStoreQualifier.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/model/SettingsData.kt
  core/designsystem/src/main/res/drawable/ic_cluster.xml
  core/designsystem/src/main/res/drawable/ic_cluster_icon.xml
  core/navigation/src/main/kotlin/com/unifest/android/core/navigation/RouteModel.kt
  core/network/build.gradle.kts
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/navigation/BoothNavigation.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/navigation/HomeNavigation.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/component/AllFestivalsRow.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/di/IntroNavigatorModule.kt
  feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/navigation/LikedBoothNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainActivity.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainTab.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/navigation/MapNavigation.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiAction.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/component/MenuItem.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/navigation/MenuNavigation.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiAction.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiState.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
  feature/menu/src/main/res/drawable-night/ic_clustering.xml
  feature/menu/src/main/res/drawable/ic_clustering.xml
  feature/menu/src/main/res/values/strings.xml
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/SplashActivity.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/SplashScreen.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/di/SplashNavigatorModule.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/viewmodel/SplashUiEvent.kt
  feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/navigation/StampNavigation.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/navigation/WaitingNavigation.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: bug, enhancement, hotfix

#271 [fix] 메뉴화면 진입시 바텀 네비게이션 바가 사라지는 문제 해결
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainTab.kt
  gradle/libs.versions.toml
Labels: bug, hotfix, skip-ci

#272 release v1.1.3
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainTab.kt
  gradle/libs.versions.toml
Labels: product, skip-ci
