Repository Project-Unifest/unifest-android, pull requests merged in 2024-05, with the labels that each got.

#126 [feat] [#38] 부스 좋아요 API 연동
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/BoothRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/BoothRepositoryImpl.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/request/LikeBoothRequest.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/LikeBoothResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/service/UnifestService.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
Labels: enhancement

#127 [feat] [#123] [#121] 홈 화면 이슈 해결 및 코드 개선
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/FestivalMapper.kt
  core/model/src/main/kotlin/com/unifest/android/core/model/FestivalTodayModel.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/FestivalResponse.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiAction.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
Labels: enhancement

#130 [feat] [#125][#98] 홈화면 API 연결, 캘린더 상태 버그 수정
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/values/strings.xml
  core/network/src/main/kotlin/com/unifest/android/core/network/response/FestivalResponse.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiAction.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
Labels: enhancement

#131 [feat] Booth 화면, Map 화면 API 연동
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/BoothMapper.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/BoothRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/BoothRepositoryImpl.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/MarkerCategory.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/Dialog.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/LoadingWheel.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/NetworkImage.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/SearchTextField.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/StarImage.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/TopAppBar.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_marker_bar.xml
  core/designsystem/src/main/res/drawable/ic_marker_bar_selected.xml
  core/designsystem/src/main/res/drawable/ic_marker_event.xml
  core/designsystem/src/main/res/drawable/ic_marker_event_selected.xml
  core/designsystem/src/main/res/drawable/ic_marker_food.xml
  core/designsystem/src/main/res/drawable/ic_marker_food_selected.xml
  core/designsystem/src/main/res/drawable/ic_marker_general_selected.xml
  core/designsystem/src/main/res/drawable/ic_marker_medical.xml
  core/designsystem/src/main/res/drawable/ic_marker_medical_selected.xml
  core/designsystem/src/main/res/drawable/ic_marker_normal.xml
  core/designsystem/src/main/res/drawable/ic_marker_toilet.xml
  core/designsystem/src/main/res/drawable/ic_marker_toilet_selected.xml
  core/designsystem/src/main/res/values/colors.xml
  core/model/src/main/kotlin/com/unifest/android/core/model/AllBoothsModel.kt
  core/model/src/main/kotlin/com/unifest/android/core/model/BoothDetailModel.kt
  core/model/src/main/kotlin/com/unifest/android/core/model/FestivalModel.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/BoothResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/service/UnifestService.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalSearchResults.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedBoothItem.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedFestivalGrid.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothLocationScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiAction.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiState.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/mapper/BoothMapper.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/model/AllBoothsMapModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/model/BoothDetailMapModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiAction.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
Labels: enhancement, design, refactor

#132 [feat] 부스 좋아요 API 연동 및 파생되는 기능 구현
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/BoothMapper.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/BoothRepositoryImpl.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/LikedBoothRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/LikedBoothRepositoryImpl.kt
  core/database/src/main/kotlin/com/unifest/android/core/database/LikedBoothDao.kt
  core/designsystem/src/main/res/values/strings.xml
  core/network/src/main/kotlin/com/unifest/android/core/network/response/BoothResponse.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedBoothItem.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothLocationScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiState.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/viewmodel/LikedBoothViewModel.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/navigation/MapNavigation.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiEvent.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
Labels: enhancement, design, hotfix

#134 [feat] Intro 화면 검색 지역 필터링 적용
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/BoothMapper.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/FestivalEntityMapper.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/FestivalMapper.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/BoothRepository.kt
  core/database/schemas/com.unifest.android.core.database.LikedFestivalDatabase/1.json
  core/database/src/main/kotlin/com/unifest/android/core/database/entity/LikedFestivalEntity.kt
  core/model/src/main/kotlin/com/unifest/android/core/model/BoothModel.kt
  core/model/src/main/kotlin/com/unifest/android/core/model/FestivalModel.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/BoothResponse.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/FestivalResponse.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalSearchResults.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedFestivalGrid.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/mapper/BoothMapper.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/model/BoothMapModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiAction.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
Labels: enhancement

#136 [feat] [#135] 맵 화면 Chips들 선택가능하게 하고, 선택된 칩에 따라 필터링 해주기
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/BoothFilterChip.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/BoothFilterChips.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiAction.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
Labels: enhancement

#139 [feat] Map 화면, 축제 BottomSheet 검색 기능 구현
  core/common/src/main/kotlin/com/unifest/android/core/common/FestivalUiAction.kt
  core/common/src/main/kotlin/com/unifest/android/core/common/utils/SearchUtils.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/SearchTextField.kt
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalSearchResults.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiAction.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
Labels: enhancement, design, hotfix

#141 [fix] 축제 바텀 시트내에 다른 축제 클릭시 스낵바 호출
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
Labels: bug

#142 [style] [#140] 스낵바 텍스트 중앙 정렬, 폰트 적용
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/BoothEntityMapper.kt
  core/database/schemas/com.unifest.android.core.database.LikedBoothDatabase/1.json
  core/database/src/main/kotlin/com/unifest/android/core/database/entity/LikedBoothEntity.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/SnackBar.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedBoothItem.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiEvent.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiEvent.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiEvent.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
Labels: enhancement, design, refactor

#144 [feat] [#52] [#143] Map 화면 클러스터링 제거 버전 구현
  core/common/src/main/kotlin/com/unifest/android/core/common/MultipleEventsCutter.kt
  core/common/src/main/kotlin/com/unifest/android/core/common/extension/Modifier.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/BoothRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/BoothRepositoryImpl.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/MarkerCategory.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/NetworkImage.kt
  core/designsystem/src/main/res/drawable/ic_image_placeholder.png
  core/designsystem/src/main/res/drawable/ic_item_placeholder.png
  core/designsystem/src/main/res/drawable/ic_marker_normal_selected.xml
  core/designsystem/src/main/res/values/strings.xml
  core/network/src/main/kotlin/com/unifest/android/core/network/service/UnifestService.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalSearchResults.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedBoothItem.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedFestivalGrid.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothLocationScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/model/BoothMapModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiAction.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
Labels: bug, enhancement, design

#145 [feat] 지도 폴리곤 적용
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothLocationScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
Labels: enhancement

#148 [chore] 아이콘 리사이징
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: design

#150 [fix] [#111] 축제 바텀시트의 온보딩 툴팁의 화살표 방향이 위로 향하고 있는 문제
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/Tooltip.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/TopAppBar.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/StarImage.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiState.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
Labels: design, refactor, hotfix

#151 [feat] 프로젝트 의존성 그래프 시각화
  README.md
  build-logic/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  build.gradle.kts
  feature/intro/build.gradle.kts
  feature/main/build.gradle.kts
  feature/navigator/src/main/kotlin/com/unifest/feature/navigator/MapNavigator.kt
  gradle/projectDependencyGraph.gradle
Labels: design, refactor

#152 [fix] 관심축제에 건대가 없을시 부스 데이터를 받아오지 못하던 버그 수정
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
Labels: bug

#161 [fix] [#157] [#158] [#159] [#160] minor bugs fix
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothLocationScreen.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
Labels: bug

#163 [chore] app version update
  build-logic/src/main/kotlin/com/unifest/android/Config.kt
Labels: product, skip-ci

#167 release v0.1.1
  README.md
  build-logic/src/main/kotlin/com/unifest/android/Config.kt
  core/designsystem/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  core/designsystem/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  core/designsystem/src/main/res/mipmap-hdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  core/designsystem/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-mdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  core/designsystem/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-xhdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  core/designsystem/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  core/designsystem/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  core/designsystem/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/values/splash.xml
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedFestivalGrid.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
Labels: product, skip-ci

#168 [fix] QA 내역 반영
  build-logic/src/main/kotlin/com/unifest/android/Config.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/AutoResizedText.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/StarImage.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
Labels: enhancement, design

#169 release v0.1.2
  build-logic/src/main/kotlin/com/unifest/android/Config.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/AutoResizedText.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/StarImage.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
Labels: product, skip-ci

#170 [feat] 유니페스 web url 연동
  .github/workflows/android-ci.yml
  build-logic/src/main/kotlin/com/unifest/android/Config.kt
  core/network/build.gradle.kts
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
  gradle.properties
Labels: bug, enhancement, refactor, product

#171 release v0.1.3
  .github/workflows/android-ci.yml
  build-logic/src/main/kotlin/com/unifest/android/Config.kt
  core/network/build.gradle.kts
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
  gradle.properties
Labels: enhancement, hotfix, product, skip-ci

#172 [chore] release 빌드시 배포 서버에 연동되도록 설정
  app/build.gradle.kts
  build-logic/src/main/kotlin/com/unifest/android/Config.kt
  core/network/build.gradle.kts
Labels: enhancement, product

#173 release v1.0.4
  app/build.gradle.kts
  build-logic/src/main/kotlin/com/unifest/android/Config.kt
  core/network/build.gradle.kts
Labels: product, skip-ci

#174 [fix] qa 2차
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/BoothMapper.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/BoothResponse.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
Labels: bug

#175 [chore] 앱 버젼 업데이트
  build-logic/src/main/kotlin/com/unifest/android/Config.kt
Labels: skip-ci

#177 [chore] 앱 버젼 업데이트
  build-logic/src/main/kotlin/com/unifest/android/Config.kt
Labels: skip-ci

#179 [fix] 폴리곤과 버그 수정
  build-logic/src/main/kotlin/com/unifest/android/Config.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiState.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
Labels: bug

#180 [chore] build-logic config 앱 버전 관련 변수 제거
  build-logic/src/main/kotlin/com/unifest/android/Config.kt
  gradle/libs.versions.toml
Labels: refactor, skip-ci

#181 [fix] 위치 권한 요청이 맵 화면 진입시 화면에 출력되지 않는 문제 해결
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/PermissionDialog.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  gradle/libs.versions.toml
Labels: bug, hotfix

#182 [fix] QA 3차
  core/designsystem/src/main/res/values/strings.xml
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  gradle/libs.versions.toml
Labels: bug, hotfix

#183 release v1.0.1
  core/designsystem/src/main/res/values/strings.xml
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiState.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/PermissionDialog.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  gradle/libs.versions.toml
Labels: product, skip-ci

#184 [style] 앱 내에 텍스트 길이 제한 및 최대 줄 수 조정
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  gradle/libs.versions.toml
Labels: design

#186 release v1.0.2
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  gradle/libs.versions.toml
Labels: product, skip-ci

#185 [style] 달력 청록점, 현재 날짜, 체크된 날짜 표시 figma 시안에 맞게 변경
  README.md
  feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
  gradle/libs.versions.toml
Labels: design

#187 release v1.0.3
  README.md
  feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
  gradle/libs.versions.toml
Labels: product, skip-ci

#188 [feat] CD 환경 구축
  .github/workflows/android-cd.yml
  .github/workflows/android-ci.yml
  .gitignore
  app/google-services.json
  gradle/libs.versions.toml
  project.dot.png
Labels: product

#189 release v1.0.4
  .github/workflows/android-cd.yml
  .github/workflows/android-ci.yml
  .gitignore
  app/google-services.json
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  project.dot.png
Labels: product, skip-ci

#191 [design] 축제 개수별 색 변경
  core/designsystem/src/main/res/drawable/ic_calender_left.xml
  core/designsystem/src/main/res/drawable/ic_calender_right.xml
  feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
  gradle/libs.versions.toml
Labels: design

#193 release v1.0.5
  README.md
  core/designsystem/src/main/res/drawable/ic_calender_left.xml
  core/designsystem/src/main/res/drawable/ic_calender_right.xml
  feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
  gradle/libs.versions.toml
Labels: product, skip-ci

#204 [feat] [#205] 연예인 이미지 롱클릭 확대 기능 구현
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/StarImage.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/StarImageDialog.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiAction.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  gradle/libs.versions.toml
Labels: enhancement, design

#206 release v1.0.7
  README.md
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/StarImage.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/StarImageDialog.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiAction.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  gradle/libs.versions.toml
Labels: product, skip-ci
