Repository Project-Unifest/unifest-android, pull requests merged in 2024-04, with the labels that each got.

#34 [feat] [#33] API 통신 환경 구축
  .github/workflows/android-ci.yml
  .idea/.gitignore
  .idea/compiler.xml
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/AndroidManifest.xml
  core/data/src/main/kotlin/com/unifest/android/core/data/MyClass.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/di/FileUtilModule.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/ResponseToEntity.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/request/BoothCreateRequest.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/request/MemberSignUpRequest.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/request/MenuCreateRequest.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/request/PostLikesRequest.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/response/BoothDetailResponse.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/response/FestivalSearchResponse.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/response/FileResponse.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/util/FileUtil.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/util/RunSuspendCatching.kt
  core/domain/src/main/kotlin/com/unifest/android/core/domain/entity/BoothCreateEntity.kt
  core/domain/src/main/kotlin/com/unifest/android/core/domain/entity/BoothDetailEntity.kt
  core/domain/src/main/kotlin/com/unifest/android/core/domain/entity/FestivalSearchEntity.kt
  core/domain/src/main/kotlin/com/unifest/android/core/domain/entity/FileEntity.kt
  core/domain/src/main/kotlin/com/unifest/android/core/domain/entity/MemberSignUpEntity.kt
  core/domain/src/main/kotlin/com/unifest/android/core/domain/entity/MenuCreateEntity.kt
  core/domain/src/main/kotlin/com/unifest/android/core/domain/entity/PostLikesEntity.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/MyClass.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/NetworkModule.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/RetrofitQualifier.kt
  gradlew.bat
  secrets.properties
Labels: enhancement

#41 [setting] [#40] 구글 지도 네이버 지도로 변경
  app/src/main/AndroidManifest.xml
  feature/map/build.gradle.kts
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: dependencies

#47 [feat] Map 화면 1차 구현
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/BoothFilterChip.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/NetworkImage.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/TopAppBar.kt
  core/designsystem/src/main/res/drawable/ic_location_gray.xml
  core/designsystem/src/main/res/drawable/ic_location_green.xml
  core/designsystem/src/main/res/values/strings.xml
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/BoothCard.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/BoothFilterChips.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/MyClass.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/map/build.gradle.kts
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
Labels: enhancement, design

#51 [feat] [#50] 앱에서 사용하는 Dialog 구현
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/Dialog.kt
  core/designsystem/src/main/res/drawable/ic_caution.xml
  core/designsystem/src/main/res/drawable/ic_network.xml
  core/designsystem/src/main/res/values/strings.xml
Labels: design

#54 [feat] [#31] Map 화면 바텀시트 구현
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/Dialog.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/OutlinedButton.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/Scaffold.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/SearchTextField.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/TopAppBar.kt
  core/designsystem/src/main/res/drawable/ic_delete_gray.xml
  core/designsystem/src/main/res/drawable/ic_delete_red.xml
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/kotlin/com/unifest/android/core/domain/entity/FestivalEntity.kt
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/BoothCard.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalSearchBottomSheet.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalSearchResults.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/InterestedFestivalGrid.kt
  feature/booth/build.gradle.kts
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/navigation/HomeNavigation.kt
  feature/intro/build.gradle.kts
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroUiState.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/map/build.gradle.kts
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/navigation/MapNavigation.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/navigation/MenuNavigation.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/WaitingScreen.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/navigation/WaitingNavigation.kt
  gradle/libs.versions.toml
Labels: enhancement, design

#66 [feat] [#37] Map 화면 클러스터링 구현 및 Map Marker, Booth HorizontalPager 연동
  build-logic/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  build-logic/src/main/kotlin/com/unifest/android/Compose.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/Scaffold.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/SearchTextField.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/TopAppBar.kt
  core/designsystem/src/main/res/drawable/ic_arrow_back_gray.xml
  core/designsystem/src/main/res/drawable/ic_dropdown.xml
  core/domain/src/main/kotlin/com/unifest/android/core/domain/entity/BoothSpot.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/BoothCard.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalSearchBottomSheet.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothLocationScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/navigation/BoothNavigation.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiState.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/navigation/HomeNavigation.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroUiState.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/map/build.gradle.kts
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/mapper/EntityToModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/model/BoothDetailModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/navigation/MapNavigation.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/navigation/MenuNavigation.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/WaitingScreen.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/navigation/WaitingNavigation.kt
  gradle/libs.versions.toml
Labels: enhancement, design

#63 [feat] [#49] Menu 및 InterestedBooths 화면 구현
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/TopAppBar.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/theme/Font.kt
  core/designsystem/src/main/res/drawable/ic_admin_mode.xml
  core/designsystem/src/main/res/drawable/ic_inquiry.xml
  core/designsystem/src/main/res/drawable/ic_selected_menu.xml
  core/designsystem/src/main/res/values/strings.xml
  feature/interested-booth/src/main/kotlin/com/unifest/android/feature/interested_booth/InterestedBoothScreen.kt
  feature/interested-booth/src/main/kotlin/com/unifest/android/feature/interested_booth/navigation/InterestedBoothNavigation.kt
  feature/interested-booth/src/main/kotlin/com/unifest/android/feature/interested_booth/viewmodel/InterestedBoothViewModel.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainTab.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/navigation/MenuNavigation.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiState.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
Labels: design

#68 [feat] 관심 부스 로컬 데이터베이스 환경 구축 및 CRUD 연동
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/AndroidRoomConventionPlugin.kt
  build-logic/src/main/kotlin/com/unifest/android/Plugins.kt
  build.gradle.kts
  core/data/build.gradle.kts
  core/data/src/main/kotlin/com/unifest/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/DBEntityToResponse.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/ResponseToDBEntity.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/ResponseToEntity.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/DefaultLikedBoothRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/LikedBoothRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/response/BoothDetailResponse.kt
  core/database/.gitignore
  core/database/build.gradle.kts
  core/database/src/main/kotlin/com/unifest/android/core/database/LikedBoothDao.kt
  core/database/src/main/kotlin/com/unifest/android/core/database/LikedBoothDatabase.kt
  core/database/src/main/kotlin/com/unifest/android/core/database/MenuListConverter.kt
  core/database/src/main/kotlin/com/unifest/android/core/database/di/DaoModule.kt
  core/database/src/main/kotlin/com/unifest/android/core/database/di/DatabaseModule.kt
  core/database/src/main/kotlin/com/unifest/android/core/database/entity/LikedBoothEntity.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/Dialog.kt
  core/designsystem/src/main/res/values/strings.xml
  core/domain/build.gradle.kts
  core/domain/src/main/kotlin/com/unifest/android/core/domain/entity/BoothDetailEntity.kt
  core/domain/src/main/kotlin/com/unifest/android/core/domain/mapper/EntityToResponse.kt
  core/domain/src/main/kotlin/com/unifest/android/core/domain/mapper/ResponseToEntity.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/EmptyLikedBoothItem.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalSearchBottomSheet.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/InterestedFestivalGrid.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedBoothItem.kt
  feature/booth/build.gradle.kts
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothLocationScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/interested-booth/src/main/kotlin/com/unifest/android/feature/interested_booth/InterestedBoothScreen.kt
  feature/interested-booth/src/main/kotlin/com/unifest/android/feature/interested_booth/navigation/InterestedBoothNavigation.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
  feature/liked-booth/.gitignore
  feature/liked-booth/build.gradle.kts
  feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/LikedBoothScreen.kt
  feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/navigation/InterestedBoothNavigation.kt
  feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/viewmodel/LikedBoothUiState.kt
  feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/viewmodel/LikedBoothViewModel.kt
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/build.gradle.kts
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/navigation/MenuNavigation.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiState.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement, design

#78 [feat] 홈과 인트로 화면의 디자인 및 논의내역 수정 사항
  core/database/schemas/com.unifest.android.core.database.LikedBoothDatabase/1.json
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedFestivalGrid.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainActivity.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainTab.kt
Labels: enhancement

#80 [feat] 온보딩 완료(툴팁 체크) 여부 DataStore 환경 구축 및 연동
  core/data/build.gradle.kts
  core/data/src/main/kotlin/com/unifest/android/core/data/di/DataSourceModule.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/OnboardingRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/OnboardingRepositoryImpl.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/MyClass.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/OnboardingDataSource.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/OnboardingDataSourceImpl.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/di/DataStoreModule.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/TopAppBar.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
Labels: enhancement, design

#87 [fix] [#79] Snackbar 위치 문제 해결 및 Booth 상세 화면 디자인 디테일 보완
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/navigation/BoothNavigation.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
Labels: bug, design

#93 [refactor] MVI 패턴으로 Migration
  core/common/build.gradle.kts
  core/common/src/main/kotlin/com/unifest/android/core/common/FestivalUiAction.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/BoothEntityMapper.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/SearchTextField.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/TopAppBar.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalSearchResults.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedBoothItem.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedFestivalGrid.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothLocationScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/navigation/BoothNavigation.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiAction.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiEvent.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
  feature/contact/src/main/kotlin/com/unifest/android/feature/contact/navigation/ContactNavigation.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiAction.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiEvent.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroUiAction.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroUiEvent.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroUiState.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/LikedBoothScreen.kt
  feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/navigation/LikedBoothNavigation.kt
  feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/viewmodel/LikedBoothUiAction.kt
  feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/viewmodel/LikedBoothUiEvent.kt
  feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/viewmodel/LikedBoothViewModel.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/navigation/MapNavigation.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiAction.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiEvent.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/navigation/MenuNavigation.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiAction.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiEvent.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/WaitingScreen.kt
Labels: enhancement, refactor

#95 [feat] [#75] 최근에 확인한 관심 축제를 저장하기 위한 DataStore 환경 구축
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/OnboardingDataSourceImpl.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/RecentLikedFestivalDataSource.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/RecentLikedFestivalDataSourceImpl.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/di/DataStoreModule.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/di/DataStoreQualifier.kt
Labels: enhancement

#96 [feat] Intro 화면 ScrollableTapRow, HorizontalPager 연동
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/SearchTextField.kt
  core/designsystem/src/main/res/values/strings.xml
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
Labels: enhancement, design

#97 [feat] [#91] 로컬 데이터 베이스 추가 구현
  core/common/src/main/kotlin/com/unifest/android/core/common/FestivalUiAction.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/FestivalEntityMapper.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/mapper/FestivalMapper.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/FestivalRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/FestivalRepositoryImpl.kt
  core/database/schemas/com.unifest.android.core.database.LikedFestivalDatabase/1.json
  core/model/src/main/kotlin/com/unifest/android/core/model/FestivalTodayModel.kt
  core/network/src/main/kotlin/com/unifest/android/core/network/response/FestivalResponse.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedFestivalGrid.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
Labels: enhancement

#103 [style] [#99] Map 화면 Horizontal Pager 애니메이션 추가 적용
  core/designsystem/src/main/res/values/strings.xml
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
Labels: design

#102 [feat] [#101] Intro 화면 관심 학교 추가 이후 다시 앱을 켰을 때, 진입되지 않도록 구현
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/OnboardingRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/OnboardingRepositoryImpl.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/OnboardingDataSource.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/OnboardingDataSourceImpl.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/LoadingWheel.kt
  core/designsystem/src/main/res/values/splash.xml
  feature/intro/src/main/AndroidManifest.xml
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroActivity.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroUiState.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
Labels: enhancement

#105 [feat] Map 화면 위치 권한 요청 flow 구현
  app/src/main/AndroidManifest.xml
  core/common/src/main/kotlin/com/unifest/android/core/common/extension/Activity.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/FestivalRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/FestivalRepositoryImpl.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/LikedFestivalRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/LikedFestivalRepositoryImpl.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/RecentLikedFestivalDataSourceImpl.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/di/DataSourceModule.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/di/DataStoreModule.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/di/DataStoreQualifier.kt
  core/designsystem/src/main/res/values/strings.xml
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/navigation/BoothNavigation.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainActivity.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/map/build.gradle.kts
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/PermissionDialog.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiAction.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiEvent.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/navigation/MenuNavigation.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiAction.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiEvent.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement, refactor

#112 [refactor] [#113] Clustering Library Migration
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/model/BoothDetailMapModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement, refactor

#115 [feat] Map Marker Click Event 구현
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
Labels: enhancement

#110 [feat] [#109] 축제 바텀시트 온보딩 툴팁 구현
  core/common/src/main/kotlin/com/unifest/android/core/common/FestivalUiAction.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/OnboardingRepository.kt
  core/data/src/main/kotlin/com/unifest/android/core/data/repository/OnboardingRepositoryImpl.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/OnboardingDataSource.kt
  core/datastore/src/main/kotlin/com/unifest/android/core/datastore/OnboardingDataSourceImpl.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/TopAppBar.kt
  core/designsystem/src/main/res/drawable/ic_selected_home.xml
  core/designsystem/src/main/res/values/strings.xml
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedFestivalGrid.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
Labels: enhancement, design

#116 [feat] [#117] 이용 문의 연동
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedFestivalGrid.kt
  feature/contact/.gitignore
  feature/contact/build.gradle.kts
  feature/contact/src/main/kotlin/com/unifest/android/feature/ContactScreen.kt
  feature/contact/src/main/kotlin/com/unifest/android/feature/contact/navigation/ContactNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/menu/build.gradle.kts
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/navigation/MenuNavigation.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiAction.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiEvent.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
  gradle.properties
  settings.gradle.kts
Labels: enhancement, refactor

#119 [Refactor] [#114] MutableList -> PersistentList 로 변경
  core/common/src/main/kotlin/com/unifest/android/core/common/FestivalUiAction.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedFestivalGrid.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiEvent.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroUiState.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/navigation/MenuNavigation.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiEvent.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiState.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
Labels: enhancement, refactor

#118 [refactor] 버그 수정 및 디자인 변경
  core/common/src/main/kotlin/com/unifest/android/core/common/utils/DateUtils.kt
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/HorizontalDivider.kt
  core/designsystem/src/main/res/drawable/ic_check.xml
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalSearchResults.kt
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedFestivalGrid.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiState.kt
Labels: enhancement
