Repository Project-Unifest/unifest-android, pull requests merged in 2025-09, with the labels that each got.

#435 fix: 가천대 축제 대비 QA 반영 및 앱 버전 업데이트(1.6.1 -> 1.6.2)
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/Scaffold.kt
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/unifest/android/core/ui/component/WaitingDialog.kt
  feature/booth-detail/src/main/kotlin/com/unifest/android/feature/booth_detail/BoothDetailScreen.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroActivity.kt
  feature/main/src/main/kotlin/com/unifest/android/feature/main/MainActivity.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/SplashActivity.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/SplashScreen.kt
  gradle/libs.versions.toml
Labels: fix

#440 fix: 가천대 축제 대비 2차 QA 반영 및 앱 버전 업데이트(1.6.2 -> 1.6.3)
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/TransformableImage.kt
  feature/map/src/main/kotlin/com/unifest/android/feature/map/component/BoothItem.kt
  feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
  gradle/libs.versions.toml
Labels: fix

#445 fix: 주간 캘린더 뷰 축제가 없을 경우에도 패딩 값 16.dp 로 조정
  feature/home/src/main/kotlin/com/unifest/android/feature/home/component/Calendar.kt
Labels: fix

#451 release v1.6.5
  Gemfile
  Gemfile.lock
  core/common/src/main/kotlin/com/unifest/android/core/common/DeviceId.kt
  core/data/api/src/main/kotlin/com/unifest/android/core/data/api/datasource/DeviceIdDataSource.kt
  core/data/api/src/main/kotlin/com/unifest/android/core/data/api/repository/WaitingRepository.kt
  core/data/impl/src/main/kotlin/com/unifest/android/core/data/datasource/DefaultDeviceIdDataSource.kt
  core/data/impl/src/main/kotlin/com/unifest/android/core/data/di/DataSourceModule.kt
  core/data/impl/src/main/kotlin/com/unifest/android/core/data/impl/repository/DefaultBoothRepository.kt
  core/data/impl/src/main/kotlin/com/unifest/android/core/data/impl/repository/DefaultLikedBoothRepository.kt
  core/data/impl/src/main/kotlin/com/unifest/android/core/data/impl/repository/DefaultLikedFestivalRepository.kt
  core/data/impl/src/main/kotlin/com/unifest/android/core/data/impl/repository/DefaultMessagingRepository.kt
  core/data/impl/src/main/kotlin/com/unifest/android/core/data/impl/repository/DefaultStampRepository.kt
  core/data/impl/src/main/kotlin/com/unifest/android/core/data/impl/repository/DefaultWaitingRepository.kt
  fastlane/Appfile
  fastlane/Pluginfile
  fastlane/README.md
  fastlane/report.xml
  feature/booth-detail/src/main/kotlin/com/unifest/android/feature/booth_detail/viewmodel/BoothDetailViewModel.kt
  gradle/libs.versions.toml
Labels: skip-ci

#456 feat: Throttling 적용한 TextButton 구현 및 반영
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/UnifestTextButton.kt
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/WaitingScreen.kt
Labels: feat

#457 release v1.6.7
  app/src/main/ic_launcher-playstore.png
  app/src/main/ic_launcher-playstore.webp
  core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/UnifestTextButton.kt
  core/designsystem/src/main/res/drawable-night/image_placeholder.png
  core/designsystem/src/main/res/drawable-night/image_placeholder.webp
  core/designsystem/src/main/res/drawable-night/item_placeholder.png
  core/designsystem/src/main/res/drawable-night/item_placeholder.webp
  core/designsystem/src/main/res/drawable/image_placeholder.png
  core/designsystem/src/main/res/drawable/image_placeholder.webp
  core/designsystem/src/main/res/drawable/item_placeholder.png
  core/designsystem/src/main/res/drawable/item_placeholder.webp
  feature/booth-detail/src/main/kotlin/com/unifest/android/feature/booth_detail/BoothDetailScreen.kt
  feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothScreen.kt
  feature/home/src/main/kotlin/com/unifest/android/feature/home/component/HomeCardNews.kt
  feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/splash/src/main/kotlin/com/unifest/android/feature/splash/viewmodel/SplashViewModel.kt
  feature/stamp/src/main/res/drawable/ic_checked_stamp.png
  feature/stamp/src/main/res/drawable/ic_checked_stamp.webp
  feature/stamp/src/main/res/drawable/ic_unchecked_stamp.png
  feature/stamp/src/main/res/drawable/ic_unchecked_stamp.webp
  feature/waiting/src/main/kotlin/com/unifest/android/feature/waiting/WaitingScreen.kt
  gradle/libs.versions.toml
Labels: skip-ci
